"""
Development-only multi-framework control summaries for local seeding.

NOT for production attestation. See scripts/data/README_DEV_COMPLIANCE_CATALOG.md.

- SOC 2: public TSC-style keys (CC*) with short paraphrased theme text.
- HIPAA: citation-style keys with brief theme paraphrases (not full regulatory text).
- NIST: public CSF 2.0 subcategory IDs with short summaries.
- HITRUST / ISO27001: synthetic DEV-* keys with representative themes only (no licensed text).
"""

from __future__ import annotations

from typing import Any

# Each row: framework_name, framework_version, control_key, title, category, description, criticality?
DEV_COMPLIANCE_CATALOG: list[dict[str, Any]] = [
    # --- SOC 2 (TSC-style keys; descriptions are dev paraphrases for keyword coverage) ---
    {
        "framework_name": "SOC 2",
        "framework_version": "2024",
        "control_key": "CC1.1",
        "title": "Integrity and Ethical Values",
        "category": "Security / Governance",
        "description": "Governance tone; written information security policy; management commitment; ethical values and security culture.",
        "criticality": "high",
    },
    {
        "framework_name": "SOC 2",
        "framework_version": "2024",
        "control_key": "CC1.2",
        "title": "Board and Management Oversight",
        "category": "Security / Governance",
        "description": "Designated individuals responsible for information security; accountability; oversight of the security program.",
        "criticality": "high",
    },
    {
        "framework_name": "SOC 2",
        "framework_version": "2024",
        "control_key": "CC2.2",
        "title": "Communication and Training",
        "category": "Security / Awareness",
        "description": "Security awareness training for employees; communication of security policies and expectations.",
        "criticality": "medium",
    },
    {
        "framework_name": "SOC 2",
        "framework_version": "2024",
        "control_key": "CC3.1",
        "title": "Risk Assessment",
        "category": "Risk Management",
        "description": "Annual and periodic risk assessments; identification and analysis of risks to the system and data.",
        "criticality": "high",
    },
    {
        "framework_name": "SOC 2",
        "framework_version": "2024",
        "control_key": "CC6.1",
        "title": "Logical and Physical Access Controls",
        "category": "Logical Access",
        "description": "Logical access security; least privilege; authentication; MFA multi-factor authentication for privileged and administrative accounts; password complexity and policies.",
        "criticality": "high",
    },
    {
        "framework_name": "SOC 2",
        "framework_version": "2024",
        "control_key": "CC6.6",
        "title": "Encryption and Data Protection",
        "category": "Encryption",
        "description": "Encryption at rest for sensitive data; industry standard encryption; key management themes.",
        "criticality": "high",
    },
    {
        "framework_name": "SOC 2",
        "framework_version": "2024",
        "control_key": "CC6.7",
        "title": "Transmission and Network Protections",
        "category": "Encryption / Network",
        "description": "Data encrypted in transit; TLS and equivalent protocols; transmission confidentiality.",
        "criticality": "high",
    },
    {
        "framework_name": "SOC 2",
        "framework_version": "2024",
        "control_key": "CC7.1",
        "title": "Vulnerability and Patch Management",
        "category": "Operations",
        "description": "Vulnerability scanning; assessments; remediation timelines; patch management and deployment discipline.",
        "criticality": "high",
    },
    {
        "framework_name": "SOC 2",
        "framework_version": "2024",
        "control_key": "CC7.2",
        "title": "System Monitoring",
        "category": "System Operations",
        "description": "Monitoring systems for suspicious activity; anomaly detection; security logging and alerting.",
        "criticality": "high",
    },
    {
        "framework_name": "SOC 2",
        "framework_version": "2024",
        "control_key": "CC7.4",
        "title": "Logging, Retention, and Incident Handling",
        "category": "Logging / Incident",
        "description": "Security logs collected and retained; log retention periods; incident response plan and security incident handling.",
        "criticality": "high",
    },
    {
        "framework_name": "SOC 2",
        "framework_version": "2024",
        "control_key": "CC8.1",
        "title": "Change Management",
        "category": "Change Management",
        "description": "Formal change management process for infrastructure and application changes; approvals and testing.",
        "criticality": "medium",
    },
    {
        "framework_name": "SOC 2",
        "framework_version": "2024",
        "control_key": "CC9.2",
        "title": "Vendor Management and Business Continuity",
        "category": "Vendor / Continuity",
        "description": "Third-party and vendor security reviews; backups; disaster recovery procedures and testing.",
        "criticality": "medium",
    },
    # --- HIPAA Security Rule (theme paraphrases; not full regulatory text) ---
    {
        "framework_name": "HIPAA",
        "framework_version": "Security Rule",
        "control_key": "164.308-a1",
        "title": "Security Management Process",
        "category": "Administrative",
        "description": "Risk analysis and risk management; security measures to protect ePHI; periodic evaluation.",
        "criticality": "high",
    },
    {
        "framework_name": "HIPAA",
        "framework_version": "Security Rule",
        "control_key": "164.308-a2",
        "title": "Assigned Security Responsibility",
        "category": "Administrative",
        "description": "Designated security official responsible for development and implementation of security policies.",
        "criticality": "high",
    },
    {
        "framework_name": "HIPAA",
        "framework_version": "Security Rule",
        "control_key": "164.308-a5",
        "title": "Security Awareness and Training",
        "category": "Administrative",
        "description": "Security awareness training; protection from malicious software; log-in monitoring.",
        "criticality": "medium",
    },
    {
        "framework_name": "HIPAA",
        "framework_version": "Security Rule",
        "control_key": "164.312-a2-iv",
        "title": "Encryption and Decryption",
        "category": "Technical",
        "description": "Encryption of ePHI at rest and when appropriate; decryption controls.",
        "criticality": "high",
    },
    {
        "framework_name": "HIPAA",
        "framework_version": "Security Rule",
        "control_key": "164.312-e1",
        "title": "Transmission Security",
        "category": "Technical",
        "description": "Integrity and encryption for ePHI in transit; TLS and equivalent protections.",
        "criticality": "high",
    },
    {
        "framework_name": "HIPAA",
        "framework_version": "Security Rule",
        "control_key": "164.312-b",
        "title": "Audit Controls",
        "category": "Technical",
        "description": "Audit logging; recording and examining activity in systems with ePHI; log retention considerations.",
        "criticality": "high",
    },
    {
        "framework_name": "HIPAA",
        "framework_version": "Privacy Rule (dev theme)",
        "control_key": "164.502-b",
        "title": "Minimum Necessary (theme)",
        "category": "Privacy",
        "description": "Minimum necessary use and disclosure of PHI; workforce training on privacy practices.",
        "criticality": "medium",
    },
    {
        "framework_name": "HIPAA",
        "framework_version": "Breach Notification (dev theme)",
        "control_key": "164.400-theme",
        "title": "Breach Response (theme)",
        "category": "Privacy / Incident",
        "description": "Breach assessment; notification workflows; incident response coordination for PHI exposure.",
        "criticality": "high",
    },
    # --- NIST Cybersecurity Framework 2.0 (public identifiers) ---
    {
        "framework_name": "NIST",
        "framework_version": "CSF-2.0",
        "control_key": "GV.PO-02",
        "title": "Policies and Procedures",
        "category": "Govern",
        "description": "Information security policy; governance documentation; roles for cybersecurity risk.",
        "criticality": "high",
    },
    {
        "framework_name": "NIST",
        "framework_version": "CSF-2.0",
        "control_key": "GV.RR-02",
        "title": "Roles and Responsibilities",
        "category": "Govern",
        "description": "Accountability; designated cybersecurity risk owners; organizational structure.",
        "criticality": "high",
    },
    {
        "framework_name": "NIST",
        "framework_version": "CSF-2.0",
        "control_key": "GV.RM-01",
        "title": "Risk Management Strategy",
        "category": "Govern",
        "description": "Risk assessment; risk response; annual and ongoing risk management activities.",
        "criticality": "high",
    },
    {
        "framework_name": "NIST",
        "framework_version": "CSF-2.0",
        "control_key": "PR.AA-05",
        "title": "Access Control and Authentication",
        "category": "Protect",
        "description": "Multi-factor authentication MFA; least privilege; administrative and privileged access; password policies.",
        "criticality": "high",
    },
    {
        "framework_name": "NIST",
        "framework_version": "CSF-2.0",
        "control_key": "PR.DS-01",
        "title": "Data-at-Rest Protection",
        "category": "Protect",
        "description": "Encryption at rest; protection of stored data; industry standard encryption.",
        "criticality": "high",
    },
    {
        "framework_name": "NIST",
        "framework_version": "CSF-2.0",
        "control_key": "PR.DS-02",
        "title": "Data-in-Transit Protection",
        "category": "Protect",
        "description": "Encryption in transit; TLS; network transmission protections.",
        "criticality": "high",
    },
    {
        "framework_name": "NIST",
        "framework_version": "CSF-2.0",
        "control_key": "PR.PS-04",
        "title": "Log Management",
        "category": "Protect",
        "description": "Logging; log retention; audit trails for security monitoring.",
        "criticality": "medium",
    },
    {
        "framework_name": "NIST",
        "framework_version": "CSF-2.0",
        "control_key": "DE.CM-01",
        "title": "Continuous Monitoring",
        "category": "Detect",
        "description": "Monitoring networks and systems; suspicious activity detection; security monitoring.",
        "criticality": "high",
    },
    {
        "framework_name": "NIST",
        "framework_version": "CSF-2.0",
        "control_key": "RS.MA-01",
        "title": "Incident Management",
        "category": "Respond",
        "description": "Incident response plan; containment; analysis; incident handling.",
        "criticality": "high",
    },
    {
        "framework_name": "NIST",
        "framework_version": "CSF-2.0",
        "control_key": "ID.RA-07",
        "title": "Vulnerability Management",
        "category": "Identify",
        "description": "Vulnerability scans; remediation timelines; patch management.",
        "criticality": "high",
    },
    {
        "framework_name": "NIST",
        "framework_version": "CSF-2.0",
        "control_key": "RC.RP-01",
        "title": "Recovery Planning",
        "category": "Recover",
        "description": "Backups; disaster recovery; restoration testing.",
        "criticality": "medium",
    },
    {
        "framework_name": "NIST",
        "framework_version": "CSF-2.0",
        "control_key": "GV.OC-05",
        "title": "Third-Party Risk",
        "category": "Govern",
        "description": "Third-party audits; vendor security assessments; supply chain risk.",
        "criticality": "medium",
    },
    {
        "framework_name": "NIST",
        "framework_version": "CSF-2.0",
        "control_key": "PR.IP-01",
        "title": "Change and Configuration Management",
        "category": "Protect",
        "description": "Change management; configuration baselines; controlled releases.",
        "criticality": "medium",
    },
    # --- HITRUST: synthetic dev keys only ---
    {
        "framework_name": "HITRUST",
        "framework_version": "CSF-dev",
        "control_key": "HITRUST-DEV-AC-01",
        "title": "Access Control (dev theme)",
        "category": "Access",
        "description": "Dev placeholder: access control; least privilege; MFA for sensitive systems.",
        "criticality": "high",
    },
    {
        "framework_name": "HITRUST",
        "framework_version": "CSF-dev",
        "control_key": "HITRUST-DEV-CRY-01",
        "title": "Encryption (dev theme)",
        "category": "Encryption",
        "description": "Dev placeholder: encryption at rest and in transit; TLS; key handling themes.",
        "criticality": "high",
    },
    {
        "framework_name": "HITRUST",
        "framework_version": "CSF-dev",
        "control_key": "HITRUST-DEV-LOG-01",
        "title": "Logging and Monitoring (dev theme)",
        "category": "Operations",
        "description": "Dev placeholder: audit logging; retention; monitoring for anomalies.",
        "criticality": "medium",
    },
    {
        "framework_name": "HITRUST",
        "framework_version": "CSF-dev",
        "control_key": "HITRUST-DEV-TP-01",
        "title": "Third-Party Assurance (dev theme)",
        "category": "Vendor",
        "description": "Dev placeholder: vendor risk; third-party assessments.",
        "criticality": "medium",
    },
    # --- ISO 27001: synthetic dev keys only (not Annex A text) ---
    {
        "framework_name": "ISO27001",
        "framework_version": "dev-themes",
        "control_key": "ISO-DEV-A-5-1",
        "title": "Information Security Policies (dev theme)",
        "category": "Organizational",
        "description": "Dev placeholder: documented information security policy; policy review cycle.",
        "criticality": "high",
    },
    {
        "framework_name": "ISO27001",
        "framework_version": "dev-themes",
        "control_key": "ISO-DEV-A-6-1",
        "title": "Roles and Screening (dev theme)",
        "category": "Human Resources",
        "description": "Dev placeholder: security responsibilities; designated roles; awareness.",
        "criticality": "medium",
    },
    {
        "framework_name": "ISO27001",
        "framework_version": "dev-themes",
        "control_key": "ISO-DEV-A-8-1",
        "title": "Change Management (dev theme)",
        "category": "Operations",
        "description": "Dev placeholder: change management process; controlled changes to systems.",
        "criticality": "medium",
    },
    {
        "framework_name": "ISO27001",
        "framework_version": "dev-themes",
        "control_key": "ISO-DEV-A-12-6",
        "title": "Technical Vulnerability Management (dev theme)",
        "category": "Technical",
        "description": "Dev placeholder: vulnerability scanning; patching; remediation timelines.",
        "criticality": "high",
    },
    {
        "framework_name": "ISO27001",
        "framework_version": "dev-themes",
        "control_key": "ISO-DEV-A-16-1",
        "title": "Incident Management (dev theme)",
        "category": "Incident",
        "description": "Dev placeholder: incident response plan; security incidents.",
        "criticality": "high",
    },
    {
        "framework_name": "ISO27001",
        "framework_version": "dev-themes",
        "control_key": "ISO-DEV-A-18-1",
        "title": "Supplier Relationships (dev theme)",
        "category": "Supplier",
        "description": "Dev placeholder: third-party security; vendor reviews.",
        "criticality": "medium",
    },
]
